shoptask/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using shoptask.Data;
using shoptask.Models;
using System.Reflection.Metadata.Ecma335;

namespace shoptask.Controllers
{
    public class DashBoardController : Controller
    {
        private static List<Product> _products = new List<Product>();
        private static List<Company> _company = new List<Company>();
        private static List<Blog> _blogs = new List<Blog>();
        private static List<Typeb> _types = new List<Typeb>();
        private readonly ApplicationDbContext _db;
        public DashBoardController(ApplicationDbContext db)
        {
            _company.Add(new Company { Id = 1, Name = "Niki" });
            _company.Add(new Company { Id = 2, Name = "Adidas" });
            _types.Add(new Typeb { Id = 1, Name = "comedy" });
            _types.Add(new Typeb { Id = 2, Name = "drama" });
            _types.Add(new Typeb { Id = 3, Name = "Action" });
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
                return View(product);
            }
           _db.products.Add(product);
           _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult ViewProduct()
        {
            var product = _db.products.Include(p => p.company).ToList();
            return View(product);

        }
        public IActionResult Delete(int id)
        {
            Product? product = _db.products.FirstOrDefault(x => x.Id == id);

            _db.products.Remove(product);
            _db.SaveChanges();

            return RedirectToAction("ViewProduct");
        }
        public IActionResult Edite(int id)
        {
            Product product = _db.products.FirstOrDefault(x => x.Id == id);

            return View(product);
        }
        [HttpPut]
        public IActionResult Edite(Product product)
        {
            Product temp = _db.products.SingleOrDefault(c => c.Id == product.Id);
            temp.Name = product.Name;
            temp.Description = product.Description;
            temp.Price = product.Price;
            temp.EnableSize = product.EnableSize;
            temp.Quantity = product.Quantity;
            temp.companyID = product.companyID;
            _db.products.Update(temp);
            _db.SaveChanges();
            return RedirectToAction("ViewProduct");
        }
        public IActionResult AddBlog()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddBlog(Blog blog)
        {
            if (!ModelState.IsValid)
            {
                return View(blog);
            }
            _db.blogs.Add(blog);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult ViewBlog()
        {
            var blog = _db.blogs.Include(p=>p.type).ToList();
            return View(blog);
        }
        public IActionResult DeleteBlog(int id)
        {
            Blog blog = _db.blogs.FirstOrDefault(x => x.Id == id);
            _db.blogs.Remove(blog);
            _db.SaveChanges();
            return RedirectToAction("ViewBlog");

        }
        public IActionResult EditBlog(int id)
        {
            Blog blog = _db.blogs.FirstOrDefault(y => y.Id == id);

            return View(blog);
        }
        [HttpPost]
        public IActionResult EditBlog(Blog blog)
        {

            Blog pl=_db.blogs.SingleOrDefault(c=>c.Id == blog.Id);
            pl.Name = blog.Name;
            pl.Price = blog.Price;
            pl.Description= blog.Description;
            pl.Quantity = blog.Quantity;
            pl.typeID = blog.typeID;
            _db.blogs.Update(pl);
            _db.SaveChanges();

            return RedirectToAction("ViewBlog");
        }


    }
}

shoptask/Views/Shared/_DashBoard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/shoptask.styles.css" asp-append-version="true" />
    <!----======== CSS ======== -->
    <link rel="stylesheet" href="~/css/DashBoardStyle/style.css">

    <!----===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <title>Admin Dashboard Panel</title>
</head>
<body>
    <nav>
        <div class="logo-name">
            <div class="logo-image">
                <img src="images/logo.png" alt="">
            </div>

            <span class="logo_name">MiniShop</span>
        </div>

        <div class="menu-items">
            <ul class="nav-links">
                <li>
                    <a asp-controller="DashBoard" asp-action="Index">
                        <i class="uil uil-estate"></i>
                        <span class="link-name">Dahsboard</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="DashBoard" asp-action="AddProduct">
                        <i class="uil uil-files-landscapes"></i>
                        <span class="link-name">Add Product</span>
                    </a>
                </li>
                <li>
                </li>
                <li>
                    <a asp-controller="DashBoard" asp-action="ViewProduct">
                        <i class="uil uil-chart"></i>
                        <span class="link-name">View Product</span>
                    </a>
                </li>
                <li>
                    <a asp-page="/Companies/Viewcompany" >
                        <i class="uil uil-chart"></i>
                        <span class="link-name">View Company</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="DashBoard" asp-action="AddBlog">
                        <i class="uil uil-thumbs-up"></i>
                        <span class="link-name">Add Blog</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="DashBoard" asp-action="ViewBlog">
                        <i class="uil uil-comments"></i>
                        <span class="link-name">View Blog</span>
                    </a>
                </li>
            </ul>

            <ul class="logout-mode">
                <li>
                    <a href="#">
                        <i class="uil uil-signout"></i>
                        <span class="link-name">Logout</span>
                    </a>
                </li>

                <li class="mode">
                    <a href="#">
                        <i class="uil uil-moon"></i>
                        <span class="link-name">Dark Mode</span>
                    </a>

                    <div class="mode-toggle">
                        <span class="switch"></span>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <section class="dashboard">
        <div class="top">
            <i class="uil uil-bars sidebar-toggle"></i>

            <div class="search-box">
                <i class="uil uil-search"></i>
                <input type="text" placeholder="Search here...">
            </div>

            <img src="images/profile.jpg" alt="">
        </div>

        <div class="dash-content">
            @RenderBody()
        </div>
    </section>

    <script src="~/js/DashBoardScripts/script.js"></script>
</body>
</html>

shoptask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - shoptask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/shoptask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">shoptask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - shoptask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>